case class NFLRow (
  time : String,
  x : Double,
  y : Double,
  s : Double,
  a : Double,
  dis : Double,
  o : Double,
  dir : Double,
  event : String,
  nflid : Int,
  displayName : Double,
  jerseyNumber : Int,
  position : String,
  team : String,
  frameId : Int,
  gameId : Int,
  playId : Int,
  playDirection : String
)
